In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print('basic slicing')
print(a)
print('sliced array:\n',a[1:3])

basic slicing
[1 2 3 4 5]
sliced array:
 [2 3]


In [6]:
# 2d array 

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('2d array:\n',arr_2d)
print('sliced array:\n',arr_2d[0,2])
print('entire first row:\n',arr_2d[0,:])
print('entire first column:\n',arr_2d[:,0])

2d array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
sliced array:
 3
entire first row:
 [1 2 3]
entire first column:
 [1 4 7]


In [10]:
# Sorting 
unsorted_arr = np.array([3, 1, 4, 2, 5])
sorted_arr = np.sort(unsorted_arr)
print('unsorted array:\n',unsorted_arr)
print('sorted array:\n',sorted_arr)

arr_2d_unsorted = np.array([[3, 1, 4], [2, 5, 0]])
sorted_arr_2d = np.sort(arr_2d_unsorted, axis=0)
print('unsorted 2d array:\n',arr_2d_unsorted)
print('sorted 2d array:\n',sorted_arr_2d)

unsorted array:
 [3 1 4 2 5]
sorted array:
 [1 2 3 4 5]
unsorted 2d array:
 [[3 1 4]
 [2 5 0]]
sorted 2d array:
 [[2 1 0]
 [3 5 4]]


In [12]:
# filter
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print('original array:\n',numbers)
print('filtered array:\n',even_numbers)

# filter with mask 

mask=numbers>5
filtered_numbers=numbers[mask]
print('filtered numbers:\n',filtered_numbers)

original array:
 [ 1  2  3  4  5  6  7  8  9 10]
filtered array:
 [ 2  4  6  8 10]
filtered numbers:
 [ 6  7  8  9 10]


In [ ]:
# fancy indexing vs np.where
arr = np.array([10, 20, 30, 40, 50])
where_indices = np.where(arr > 25)
print('where indices:\n',where_indices)

condition_array=np.where(arr>25, arr, -1)
print('condition array:\n',condition_array)


where indices:
 (array([2, 3, 4]),)


ValueError: either both or neither of x and y should be given