In [ ]:
import time
import numpy as np

print('numpy version:', np.__version__)

# small smoke test
arr = np.arange(6).reshape(2,3)
print('array:\n', arr)


In [31]:
import time 
arr=np.array([1,2,3,4,5])
darr=np.array([[1,23,34],[33,223,45]])
start=time.time()
print(arr*2)
print('list',darr*2)
np_array=np.arange(1,100)
print(np_array)
print('time taken:',time.time()-start)

[ 2  4  6  8 10]
list [[  2  46  68]
 [ 66 446  90]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
time taken: 0.001758575439453125


In [49]:
# vector,matrix and tensor 

vector = np.array([1,2,3])
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print('vector:\n',vector)
print('matrix:\n',matrix) 
print('tensor:\n',tensor)

vector:
 [1 2 3]
matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
tensor:
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [51]:
# Array properties 

arr=np.array([[1,2,3],[4,5,6]])
print('array:\n',arr)
print('shape:',arr.shape)
print('size:',arr.size)
print('dtype:',arr.dtype)

array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
size: 6
dtype: int64


In [ ]:
# Array Reshaping 
import numpy as np
arr=np.arange(1,11)
print('original array:\n',arr)
print('reshaped array:\n',arr.reshape(2,5))
print('reshaped array:\n',arr.reshape(5,2))
print('Flattened array:\n',arr.reshape(5,2).flatten())
print('raval array:\n',arr.reshape(5,2).ravel())

original array:
 [ 1  2  3  4  5  6  7  8  9 10]
reshaped array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
reshaped array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Flattened array:
 [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# creating array from scratch 
zeros=np.zeros((3,4))
print('zeros:\n',zeros)

ones=np.ones((2,3))
print('ones:\n',ones)


full=np.full((3,4),8)
print('full:\n',full)

random=np.random.random((2,3))
print('random:\n',random)

seq=np.arange(1,10,2)
print('seq:\n',seq)


<!-- Array Reshaping -->